#!/bin/sh
# postinst script for cloudgw

set -e

case "$1" in
    configure)
      systemctl daemon-reload
      systemctl enable cloudgw.service
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0